name: Build & Upload APK

on:
  push:
    paths:
      - 'android/app/src/main/AndroidManifest.xml'
      - 'lib/my_home_page.dart'
      - 'lib/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set APK File Name
        id: set_apk_name
        run: |
          # commit_message=$(git log -1 --pretty=%B)
          # apk_name="${commit_message// /_}_app.apk"
          apk_name="my_app.apk"
          echo "APK_NAME=$apk_name" >> $GITHUB_ENV
          echo $apk_name

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.8'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK and App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: build/app/outputs/flutter-apk/

      - name: FTP Transfer
        uses: joutvhu/ftp-transfer@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          commands: |
            put ./build/app/outputs/flutter-apk/ ./
            rename app-release.apk ${{env.APK_NAME}}
            delete app-release.apk.sha1
